steps:
  - group: ":snyk: Snyk Scans"
    key: "snyk"
    steps:
    - label: ":snyk: OSS Scan"
      plugins:
      - /Users/jeremy/dev/plugins/snyk-buildkite-plugin#snyk-mvp:
          scan: 'oss'
          token-env: 'BUILDKITE_SNYK_TOKEN'
          annotate: true

    - label: ":snyk: Code scan"
      plugins:
      - /Users/jeremy/dev/plugins/snyk-buildkite-plugin#snyk-mvp:
          scan: 'code'
          token-env: 'BUILDKITE_SNYK_TOKEN'
      
    - label: ":snyk: Container Scan"
      plugins:
      - /Users/jeremy/dev/plugins/snyk-buildkite-plugin#snyk-mvp:
          scan: 'container'
          token-env: 'BUILDKITE_SNYK_TOKEN'
          image: alpine
